name: GraphParser CI Flow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  graphparser-build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Source Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK environment
      - name: Configure JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      # Step 3: Build and Compile with Maven
      - name: Compile Project with Maven
        run: mvn clean install

      # Step 4: Run Unit Tests with Maven
      - name: Execute Unit Tests
        run: mvn test

